### PR TITLE
Installation setup docker

### PR DESCRIPTION
**Pull request by rudijs**
Hi,

As discussed in issue https://github.com/elastic/examples/issues/18 here's an initial draft of an ELK stack Docker setup.

Please review and edit anywhere you deem appropriate.

Thanks.

### CODE REVIEW

**Comment by asawariS** [comment]
Hi Rudy, 

I have pushed some minor changes to the ReadMe on the PR branch.
- added a community contribution to acknowledge you for the example
- made some minor cosmetic tweaks. 

Could you take a look, and also address the following: 
- Add ELK and Docker version that this was tested in (in the contribution header)
- I had trouble running this on OSX, and I think it was because of this issue: https://github.com/boot2docker/boot2docker/issues/581. Basically, /usr/share/elasticsearch/data is not writable, and chmod does not help. I noticed that you mention that this has been tested in Linux. If you have time, feel free to add OSX / Windows instructions (when applicable). Alternatively, emphasize the Linux-ONLY nature of this example in the header. Either option works. 

Thanks
Asawari

**Comment by rudijs** [comment]
Hey Asawari,

I've added the software versions and comments on the linux only nature of
the example.

I'm 100% Ubuntu here (workstation and servers) so I'm not able to test
OSX/Windows.

Hopefully we'll get some community input for that.

**Comment by asawariS** [comment]
Perfect. I have merged your example to the main repo. Thanks a bunch for the contribution!!

**Comment by rudijs** [comment]
@asawariS Great, all good!

There's a couple other scenarios/examples I could contribute in the future as well.

I though we'd get through this one and let it settle then see about some more.

The two I'm thinking of are again Dockerized containers for:

1) RELK stack .. R = RabbitMQ.

Basically RabbitMQ works as a broker in the stack. Logstash "publishers" put messages on to a RabbitMQ queue and Logstash "consumer" pulls them off and into Elastciseach.

This is what I use in production.

Pros are things like you can see how fast messages are flowing, can stop/start Logstash and Elasticsearch without losing messages as they stay on the queue.

Cons would include added complexity - another moving Part.

2) Logstash-forwarder: https://github.com/elastic/logstash-forwarder

A logstash docker container that mounts volumes from another container and send it's logfiles Logstash.


Do you think these also would be worthwhile additions?

**Comment by asawariS** [comment]
@rudijs 

I think the RabbitMQ+ELK example would be a great addition. 

With regards to Logstash Forwarder, that's functionality will soon be moved to Filebeat (https://github.com/elastic/filebeat) in the Beats framework. So, I would hold off on that example for now, and perhaps create something with Filebeat in the future. You can read more about the roadmap here: https://www.elastic.co/guide/en/logstash-roadmap/current/index.html#_logstash_forwarder

Thanks for the examples, and looking forward to more contributions from you!!

**Comment by rudijs** [comment]
@asawariS 

OK cool .. sounds all good.

That's interesting stuff regarding Filebeat - just goes to show that when you contribute you also learn and improve yourself.

I'm a fan boy of Logstash Forwarder and have checked out PacketBeat already (videos only), so for sure I'll be following up on that in due time.

Anyways then I'll see you around here on the githubs.

Cheers.

**Pull request merged**
