### PR TITLE
Fix/improve watcher test scripts: YAML support, metadata-git-commit, better error handling, --cacert, multiple time fields

### PR DESCRIPTION
**Pull request by ypid-geberit**
Using YAML comes in handy for bigger watches 😉

### CODE REVIEW

**Comment by ypid-geberit** [comment]
As far as I can tell, the version of `run_test.py` in master is incompatible with ES 7.x. Any plans to merge those improvements?

**Comment by DanRoscigno** [comment]
@ypid-geberit :
Hi Robin, if you can rebase this I will review the parts that I understand, and I will look for reviewers for the parts that I do not personally know about.  Sorry for letting this sit for so long!

**Comment by ypid-geberit** [comment]
Done that. I went with merging the latest master into my branch which was way easier because here in this PR, I did some radical changes of `run_test.py` early on which git rebase cannot resolve automatically.

Note that we could drop `--minify-scripts` which was a workaround for ES before 6.6.0.

**Review by DanRoscigno — COMMENTED** [review]
run_all_tests.sh LGTM

@gingerwizard can you have a look at the diffs to run_all_tests.py

@legalastic can you comment on the copyright lines of run_all_tests.py:
# SPDX-FileCopyrightText: 2017 Dale McDiarmid <dalem@elastic.co>
 # SPDX-FileCopyrightText: 2017-2020 Robin Schneider <robin.schneider@geberit.com>
 # SPDX-FileCopyrightText: 2020 Dan Roscigno <dan@roscigno.com>
 # SPDX-License-Identifier: Apache-2.0

run_test.sh LGTM

**Comment by ypid-geberit** [comment]
Ping @DanRoscigno, @legalastic @gingerwizard 

I still think this is a useful enhancement. What do you think?

**Comment by ypid-geberit** [comment]
@DanRoscigno, @legalastic @gingerwizard: Any chance of getting this merged?

**Comment by DanRoscigno** [comment]
Done, thanks @ypid-geberit

**Comment by ypid-geberit** [comment]
So long and then so quickly merged. You are welcome, thanks for merging :)

**Pull request merged**
