### PR TITLE
Configs for metricbeat and filebeat on EKS

### PR DESCRIPTION
**Pull request by asjadathick**
This example adds Kubernetes configuration files to run Metricbeat and Filebeat on [Amazon EKS ](https://aws.amazon.com/eks/). EKS is slightly different in what comes OOTB compared to vanilla k8s that  we reference in our [documentation](https://github.com/elastic/beats/tree/master/deploy/kubernetes).

I will also be referencing this example in a blog post on Monitoring EKS. 

Appreciate a quick review. Thanks!

### CODE REVIEW

**Comment by DanRoscigno** [comment]
@asjadathick I would suggest adding a README.md for people that arrive at the page without seeing the blog.  I generally put the instructions in both the blog and the README, and then I keep the instructions updated in the README as versions change etc.

**Comment by DanRoscigno** [comment]
@asjadathick In lines 12-15 of filebeat.yaml you have setup dashboards, because you are deploying a DaemonSet the setup is going to happen over and over.  I would move setup into a one-time job like in this [Metricbeat example](https://github.com/elastic/examples/blob/master/MonitoringKubernetes/metricbeat-kubernetes.yaml#L27-L78). I can't review the rest of the files today as I have something else urgent.  If you want to ping me from the blog ticket I am happy to look at that with you later on.

**Comment by asjadathick** [comment]
Good feedback @DanRoscigno. I've updated the configs for both filebeat and metricbeat to use a batch job to run setup; will add a README shortly. Let me know if you have time to go through the rest of the example and give it an OK. Thanks! 

(I'll link this to the blog issue for your visibility)

**Comment by asjadathick** [comment]
I've added a README detailing the example with step by step instructions. The blog post link is a placeholder at the moment; I will update this once I've got the link.

@DanRoscigno & @jamiesmith, would appreciate a quick review and approval to merge the content. I will merge and close this PR once I get the blog post link.

Thank you!

**Comment by DanRoscigno** [comment]
LGTM, go ahead and merge it if you are ready. @asjadathick

**Pull request merged**
